// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful to verify MCP connectivity and auth.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }, ctx) => ({
    content: [
      {
        type: "text",
        text: ctx.isAuthenticated() ? `Hello ${ctx.getUserEmail() ?? ctx.getUserId() ?? "user"}: ${text}` : text
      }
    ]
  })
});

// src/lib/mcp/tools/fetch-race-ranking.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var fetch_race_ranking_default = defineTool2({
  name: "fetch_race_ranking",
  title: "Fetch race ranking",
  description: "Given a public race results/leaderboard URL and one or more BIB numbers, fetch the current overall rank, elapsed time, status, and last checkpoint for each BIB. Uses AutoLap's server-side scraper.",
  inputSchema: {
    url: z2.string().url().describe("Public race results/leaderboard URL."),
    bibs: z2.array(z2.string().min(1)).min(1).describe("BIB numbers to look up (strings).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ url, bibs }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!supabaseUrl || !anonKey) {
      return {
        content: [{ type: "text", text: "Server not configured (missing SUPABASE_URL / anon key)." }],
        isError: true
      };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/fetch-ranking`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anonKey}`,
        apikey: anonKey
      },
      body: JSON.stringify({ url, bibs })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Ranking fetch failed (${res.status}): ${JSON.stringify(data).slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data.rankings ?? [], null, 2) }],
      structuredContent: { rankings: data.rankings ?? [], fetchedAt: data.fetchedAt ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wgfritttjktcxaufdxku";
var mcp_default = defineMcp({
  name: "autolap-scanner-mcp",
  title: "AutoLap Scanner",
  version: "0.1.0",
  instructions: "Tools for the AutoLap Scanner app. Use `echo` to verify connectivity, or `fetch_race_ranking` to look up a runner's current rank and last checkpoint from a public race results URL.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, fetch_race_ranking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
